//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace symphony_limited.Areas.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class academy
    {
        public int AcademyId { get; set; }
        public string TeacherId { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Fanbage { get; set; }
    }
}
