//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace symphony_limited.Areas.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public string CourseId { get; set; }
        public string NameCourse { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string status { get; set; }
        public string desscription { get; set; }
        public Nullable<System.DateTime> numberofsession { get; set; }
        public string NameSubject { get; set; }
        public Nullable<int> TeacherId { get; set; }
    }
}
